Text input demo
LandRegistry/hmlr-design-system-legacy pull request #12
Opened 2019-03-05 08:34 UTC by mick-jones

- Import added for text-input styles
- README.md file added for text-input demo
- Macros added for text-input and textarea components
- Styles added to correct font sizing for hints and error messages

2019-03-07 10:30 UTC, andymantell requested changes

2019-03-07 10:30 UTC, andymantell commented on hmlr_design_system/components/text-input/demos/demo.html
> +          "placeholder": "Start typing here"
It's generally suggested not to use placeholder text as it disappears as soon as you start typing. Anything that people actually need to know in order to fill out the field should go in form hints.

If people do decide to use placeholders that's up to them, but it might be best to steer clear of demoing them here lest it be seen as a "recommendation"

2019-03-07 10:30 UTC, andymantell commented on hmlr_design_system/components/text-input/style.scss
> +  &:focus {
Don't think this focus style needs re-specifying? It's already there on the base gov styles?

2019-03-07 13:55 UTC, mick-jones commented on hmlr_design_system/components/text-input/demos/demo.html
> +          "placeholder": "Start typing here"
Agreed. I was simply following the prototype, but GDS strongly recommend not using them, so I will remove

2019-03-08 09:36 UTC, andymantell approved these changes

2019-03-08 09:36 UTC, merged