Links demo
LandRegistry/hmlr-design-system-legacy pull request #13
Opened 2019-03-06 10:24 UTC by mick-jones

- Added styles for alternative link design to global.scss
- Also extended govuk-link to .hmlr-link to avoid confusion

2019-03-07 10:42 UTC, andymantell requested changes

2019-03-07 10:42 UTC, andymantell commented on hmlr_design_system/settings/global.scss
> +body {
If you specify the `$govuk-font-family` variable, it shouldn't be necessary to reassign the font family here - it will just get picked up by the underlying gov code. This is already done here:

https://github.com/LandRegistry/hmlr-design-system/blob/develop/demo/assets/src/scss/main.scss#L4

At the moment that lives in the demo's main.scss file. I don't mind if you want to move it out of there and into this settings file, but at the moment it's kinda being done twice.

2019-03-07 10:42 UTC, andymantell commented on hmlr_design_system/settings/global.scss
> +.hmlr-link--secondary {
Because this link class is being redefined without inheriting anything from the gov kit, it is missing the focus styles. It should either:

- `@extend %govuk-link` like the other one does
OR
- Use the `govuk-focusable-fill` mixin.

I would probably prefer the @extend option

2019-03-07 15:49 UTC, mick-jones commented on hmlr_design_system/settings/global.scss
> +body {
Have moved this into globals

2019-03-08 09:17 UTC, andymantell approved these changes

2019-03-08 09:17 UTC, merged