Add back buttons
LandRegistry/hmlr-design-system-legacy pull request #15
Opened 2019-03-08 15:02 UTC by mick-jones

- Back button component added to all demo pages

- There seems to be quite a bit of padding at the top of the page. Do you want to reduce this before merging, or are you happy with it?

2019-03-11 10:30 UTC, andymantell requested changes

2019-03-11 10:30 UTC, andymantell commented on hmlr_design_system/components/button/demos/demo.html
> +{% block beforeContent %}
@mick-jones I reckon we should move this to the base layout.html template rather than repeating it in here?

If there's specific cases where you _don't_ want a back link, you can then override the block and empty it out.

2019-03-11 15:36 UTC, mick-jones commented on hmlr_design_system/components/button/demos/demo.html
> +{% block beforeContent %}
Done

2019-03-13 09:20 UTC, andymantell approved these changes

2019-03-13 09:20 UTC, merged