Checkboxes demo
LandRegistry/hmlr-design-system-legacy pull request #21
Opened 2019-03-12 08:39 UTC by mick-jones

- Added checkbox component
- Stylesheet added for new smaller checkboxes
- Demo added for checkboxes
- back link url has been set so back button will appear when merged into develop with branch 'add-back-links'

2019-03-12 09:15 UTC, andymantell requested changes

2019-03-12 09:15 UTC, andymantell commented on hmlr_design_system/components/checkboxes/style.scss
> +      width: 26px;
@mick-jones Could these be 24px like the radios? So that if/when https://github.com/alphagov/govuk-frontend/pull/1125 is merged, we can remove this code without any significant visual change

2019-03-12 09:15 UTC, andymantell commented on hmlr_design_system/components/checkboxes/style.scss
> +      +.govuk-checkboxes__label {
Minor point, but a space after the plus would be good

2019-03-12 09:15 UTC, andymantell commented on hmlr_design_system/settings/variables.scss
> +$border: #bfc1c3;
This variable name feels a bit vague. What border? More broadly I think we need a bit more structure here, but we can do that as part of a bigger review this week. Maybe for now just tweak the name of this variable to describe what it is.

2019-03-12 11:36 UTC, mick-jones commented on hmlr_design_system/components/checkboxes/style.scss
> +      width: 26px;
hmm. I'm not feeling good about making changes to Aga's designs here and there. Whether we use the current radios, or the new smaller ones when they arrive, I think that we should be sticking fairly rigidly to her designs. This goes for the radios too.

2019-03-12 11:56 UTC, mick-jones commented on hmlr_design_system/settings/variables.scss
> +$border: #bfc1c3;
Updated

2019-03-13 11:09 UTC, andymantell commented on hmlr_design_system/components/checkboxes/style.scss
> +      width: 26px;
Resolving this as it's gonna be dealt with elsewhere

2019-03-13 11:10 UTC, merged