Hmlr layout
LandRegistry/hmlr-design-system-legacy pull request #32
Opened 2019-03-20 14:59 UTC by mick-jones

- Added new header component & demo for internal apps. (Reinstated the header component)
- Added new typography demo
- Added a left column to standard layout, made page 100% width. Left column is currently set at 300px, More options for this should be added in a future branch. maybe add options for 200px, 250px and 350px. More layout options to be added in future branch. e.g 3 column and 1 column layouts
- Added row and 2/3 width column containers on all main content
- Made SASS variable names more sensible i.e $font-color--meta
- Footer and header components can how have additional classes
- Mixins file added with media query mixins

2019-03-22 14:10 UTC, andymantell requested changes

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/footer/style.scss
> +  &.demo {
Could you either:

- Remove this from the component's stylesheet, and hard code it in a <style> block in the demo page template (To keep it out of the built output)

OR

- Add a legitimate variant like `.hmlr-footer--static` which people could use if they didn't want a sticky footer.

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/header-internal/style.scss
> +@import '../../utilities/hexa-border';
This one doesn't need to import the slanty border

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/header/README.md
> +# Header this
What's this "this"? :-)

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/header/style.scss
> +  .hmlr-header__inner {
These sub-elements of hmlr-header don't need to be nested inside the parent class. The structure is implied by BEM, and one of the principles of BEM is to keep specificity as flat as possible, only nesting where necessary.

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/links/style.scss
> +  color: $font-color;
This link is appearing in blue, despite being overriden to black because the govuk link puts the color style on the `:link` pseudo class. If you scope this color override inside `&:link { color: $font-color }` it should work then

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/settings/global.scss
> +  display: flex;
Bear in mind that people may wish to use some of these components without using the new layout so sticking this stuff on the top level .hmlr-theme doesn't feel quite right.

I think the layout should be a "component" in it's own right (And we can argue about different words other than component later). It should be in it's own _optionally includable_ partial.

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/settings/global.scss
> +  font-family: Arial, Helvetica, sans-serif;
This font-family stuff used to live in `demo/assets/src/scss/main.scss` but it's arrived back here again? I would prefer that the overall font stuff be a property of the application that is consuming the design system, because I don't want to preclude these components from ever being used on an external facing service that might use the Transport font for example. Granted, the components we have here now probably won't be, but we may put stuff in here that could feasibly be useful for both internal _and_ external stuff.

The line of code use to be this, in main.scss

```
$govuk-font-family: "Arial", sans-serif;
```

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/settings/global.scss
> +    @include tablet-portrait {
There's media query mixins based on sass-mq built into the gov kit, it'd be preferable to stick to those. They're pretty flexible, we should be able to achieve everything we need with them:

https://github.com/alphagov/govuk-frontend/blob/master/src/helpers/_media-queries.scss

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/header-internal/README.md
> +{{ header({
This, and the React example below need to be updated to say "headerInternal"

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/header-internal/component.js
> +function Header(props) {
This should probably be HeaderInternal for consistency?

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/header-internal/style.scss
> +.hmlr-header--internal {
Strictly speaking this isn't a variant of hmlr-header in that it does not depend in any way upon it. So this should be `hmlr-header-internal` with a single hyphen

2019-03-22 14:10 UTC, andymantell commented on hmlr_design_system/components/header/style.scss
> +  width: 100%;
Shouldn't need width: 100% here? An unfloated div will naturally go to full width. Was there another reason for this being specified?

2019-03-22 14:44 UTC, mick-jones commented on hmlr_design_system/components/footer/style.scss
> +  &.demo {
.hmlr-footer--static seemed like the better option, so that has been added

2019-03-22 14:57 UTC, mick-jones commented on hmlr_design_system/components/links/style.scss
> +  color: $font-color;
I've added this. It didn't seem to be a problem for me, could it be a browser specific thing? Although I imagine you're using Chrome?

2019-03-22 15:46 UTC, mick-jones commented on hmlr_design_system/settings/global.scss
> +    @include tablet-portrait {
Will fix in 2 PRs time

2019-03-28 07:55 UTC, andymantell commented on hmlr_design_system/settings/global.scss
> +    @include tablet-portrait {
Raised as https://github.com/LandRegistry/hmlr-design-system/issues/35 to pick up later

2019-03-28 07:58 UTC, andymantell commented on hmlr_design_system/settings/global.scss
> +  display: flex;
Raised as https://github.com/LandRegistry/hmlr-design-system/issues/36 to pick up later

2019-03-28 08:00 UTC, andymantell approved these changes

2019-03-28 08:00 UTC, merged