panel styles
LandRegistry/hmlr-design-system-legacy pull request #42
Opened 2019-05-01 15:21 UTC by mick-jones

2019-05-01 15:22 UTC, mick-jones commented
- Added stylesheet for panel component
- Added panel demo

2019-05-28 10:20 UTC, andymantell requested changes

2019-05-28 10:20 UTC, andymantell commented on hmlr_design_system/components/panel/style.scss
> +  background-color: $govuk-brand-colour;
@mick-jones I'm inclined to think this should be a new variant really rather than overriding a current one.

Overriding the font-size I guess I can understand, but I don't think we should change the colour of an existing variant.

2019-05-28 10:24 UTC, andymantell requested changes

2019-05-28 10:24 UTC, andymantell commented on hmlr_design_system/components/panel/style.scss
> +  padding: 20px;
Also, other modifications such as font sizes should be scoped as the other components have been, to `.hmlr-theme {}`

2019-10-11 08:55 UTC, closed without merging