Webpack and react refactor
LandRegistry/hmlr-design-system-legacy pull request #9
Opened 2019-02-28 08:44 UTC by andymantell

2019-03-14 12:59 UTC, mick-jones commented on hmlr_design_system/components/footer/README.md
> +<Footer>
Maybe this could be split into 2 examples, one with anchors and one with <Link />, or just stick with one type. As a  copy & paste example, it might be more useful. Just a suggestion.

2019-03-14 13:05 UTC, mick-jones commented on hmlr_design_system/components/footer/demos/demo.html
> +          'text': '© Crown copyright',
&copy; Not sure if this is still a thing, but would an ascii code be better here?

2019-03-14 13:39 UTC, mick-jones commented on hmlr_design_system/components/footer/demos/demo.html
> +      }, '© Crown copyright')
again, would ascii code be better here?

2019-03-14 13:45 UTC, mick-jones commented on hmlr_design_system/components/footer/component.js
> +      { props.children && (
Again, just a suggestion. I would do the logic outside of the return, and pass it into my jsx as a variable, that way I'm only returning jsx and can also lose the <>

2019-03-14 13:47 UTC, mick-jones requested changes
A couple of suggestions and question about the copy-write and ascii.

2019-03-18 08:44 UTC, andymantell commented on hmlr_design_system/components/footer/README.md
> +<Footer>
@mick-jones I think we just need to review the presentation and documentation of all the components full stop, let's pick this up then

2019-03-18 09:21 UTC, andymantell commented on hmlr_design_system/components/footer/demos/demo.html
> +          'text': '© Crown copyright',
As discussed, and as per https://www.w3.org/International/questions/qa-escapes#use I don't believe we need to do this. If someone needed to insert an ampersand, they could do it by marking the string with the jinja `|safe` filter.

In the JSX example, we wouldn't need to do this anyway, because the only reason for escaping is to stop it being treated like a piece of the underlying _markup_, which isn't true in JSX - it's just a string.

2019-03-18 09:21 UTC, andymantell commented on hmlr_design_system/components/footer/demos/demo.html
> +      }, '© Crown copyright')
See other comment - no....

2019-03-18 09:33 UTC, andymantell commented on hmlr_design_system/components/footer/component.js
> +      { props.children && (
Sorted

2019-03-18 09:46 UTC, merged